set(var1 "abbbbbd")
string(REGEX REPLACE "^ab+d$" "x" result1 ${var1})
message(${result1})
string(REGEX REPLACE "^a(b+d)$" "x" result2 ${var1})
message(${result2})
string(REGEX REPLACE "(^ab)+(d$)" "x" result3 ${var1})
message(${result3})
message("\n")

set(var2 "ab12345cd")
string(REGEX REPLACE "^ab|cd$" "x" result4 ${var2})
message(${result4})
string(REGEX REPLACE "(^ab)|(cd$)" "x" result5 ${var2})
message(${result5})
string(REGEX REPLACE "^a(b|c)d$" "x" result6 ${var2})
message(${result6})
message("\n")

set(var3 "ab")
string(REGEX REPLACE "^(ab|cd)$" "x" result7 ${var3})
message(${result7})
string(REGEX REPLACE "^((ab)|(cd))$" "x" result8 ${var3})
message(${result8})
string(REGEX REPLACE "^((ab|c)d)$" "x" result9 ${var3})
message(${result9})