macro(foo)
	set(OPTIONS OPTIONAL FAST)
	set(ONE_VALUE_ARGS SOURCE DESTINATION)
	set(MULTI_VALUE_ARGS TARGETS CONFIGURATIONS)
	cmake_parse_arguments(FOO "${OPTIONS}"
		"${ONE_VALUE_ARGS}" "${MULTI_VALUE_ARGS}" ${ARGN})
endmacro()

foo(TARGETS a b SOURCE xxx DESTINATION yyy OPTIONAL asdf CONFIGURATIONS)

message("FOO_OPTIONAL = ${FOO_OPTIONAL}")
message("FOO_FAST = ${FOO_FAST}")
message("FOO_SOURCE = ${FOO_SOURCE}")
message("FOO_DESTINATION = ${FOO_DESTINATION}")
message("FOO_TARGETS = ${FOO_TARGETS}")
message("FOO_CONFIGURATIONS = ${FOO_CONFIGURATIONS}")
message("FOO_UNPARSED_ARGUMENTS = ${FOO_UNPARSED_ARGUMENTS}")
message("FOO_KEYWORDS_MISSING_VALUES = ${FOO_KEYWORDS_MISSING_VALUES}")